# google-chrome-stable & chrome-driver
---
- hosts: localhost
  become: true
  tasks:
  - name: install chrome
    shell: |
	     sudo apt update
	     sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
	     sudo echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
	     sudo apt-get -y update
	     sudo apt-get -y install google-chrome-stable
  - name: download and setup shrome driver permissions
    shell: |
       sudo wget https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_linux64.zip	
	     sudo apt install unzip
	     unzip chromedriver_linux64.zip
	     sudo mv chromedriver /usr/bin/chromedriver
	     sudo chown root:root /usr/bin/chromedriver
	     sudo chmod +x /usr/bin/chromedriver
